### ISSUE TITLE
A substitute for xlwings 

### ISSUE THREAD

**Issue by lyralan** [LBNL-ETA/Adapter#10]
The use of xlwings in Adapter keeps asking permissions to open excel files to extract table ranges, which could be distracting when there's multiple input files. https://github.com/LBNL-ETA/Adapter/blob/95362e09d51a1a4d5dea768c842d6f49fd45cb73/adapter/comm/excel.py#L6

A potential substitute function for handeling excel table ranges without actually opening files can be `data_frame_from_xlsx` (https://stackoverflow.com/questions/20486453/reading-an-excel-named-range-into-a-pandas-dataframe).

**Comment by lyralan** [comment]
I wrote a few lines that have the same functions as adapter.to_python.Excel https://github.com/LBNL-ETA/Adapter/blob/95362e09d51a1a4d5dea768c842d6f49fd45cb73/adapter/i_o.py#L508 and tested with WICF and CRE shipments inputs - the shipment analysis ran through smoothly without opening the excel files.

**Comment by milicag** [comment]
@lyralan Thanks for your suggestion. A couple of questions:
Have you run the tests with the substitute? Does it cover the entire adapter functionality that the import your are suggesting we replace currently covers?
Do you know if the package you are suggesting we use is being regularly maintained?

**Comment by milicag** [comment]
What I'd be super happy about is if we could somehow prevent those errors when Excel gets stuck with some background process at file creation, if some files were previously getting opened. Maybe this would actually prevent those errors.

**Comment by lyralan** [comment]
> @lyralan Thanks for your suggestion. A couple of questions: Have you run the tests with the substitute? Does it cover the entire adapter functionality that the import your are suggesting we replace currently covers? Do you know if the package you are suggesting we use is being regularly maintained?

@milicag I've run a few tests on WICF and CRE Shipments only with the following sample code, the package used in which seems to be regularly maintained (last update on Sep 23, 2021 https://openpyxl.readthedocs.io/en/stable/)
```
import openpyxl
wb = openpyxl.load_workbook(file_path, data_only=True, read_only=False, keep_vba=True)

def df_from_xlsx(wb, range_name):
    """ Get a single rectangular region from the specified file.
    range_name can be a standard Excel reference ('Sheet1!A2:B7') or 
    refer to a named region ('my_cells')."""
    if not isinstance(range_name, str):
        region = range_name
    elif '!' in range_name:
        # passed a worksheet!cell reference
        ws_name, reg = range_name.split('!')
        if ws_name.startswith("'") and ws_name.endswith("'"):
            # optionally strip single quotes around sheet name
            ws_name = ws_name[1:-1]
        region = wb[ws_name][reg]
    else:
        # passed a named range; find the cells in the workbook
        full_range = wb.get_named_range(range_name)
        if full_range is None:
            raise ValueError(
                'Range "{}" not found in workbook "{}".'.format(range_name, xlsx_file)
            )
        # convert to list (openpyxl 2.3 returns a list but 2.4+ returns a generator)
        destinations = list(full_range.destinations) 
        if len(destinations) > 1:
            raise ValueError(f'Range "{range_name}" in contains more than one region.')
        ws, reg = destinations[0]
        # convert to worksheet object (openpyxl 2.3 returns a worksheet object 
        # but 2.4+ returns the name of a worksheet)
        if isinstance(ws, str):
            ws = wb[ws]
        region = ws[reg]
    if isinstance(region, tuple):
        df = pd.DataFrame([[cell.value for cell in row] for row in region[1:]], columns=[cell.value for cell in region[0]])
    else:
        df = pd.DataFrame([[region.value]], columns=[range_name])
    return df
dict_of_dfs = {x.name: df_from_xlsx(wb, x.name) for x in wb.defined_names.definedName}
for ws in wb.worksheets:
    for k, v in ws.tables.items():
        dict_of_dfs[k] = df_from_xlsx(wb, ws[v])
for df in dict_of_dfs.values():
    df.columns = process_column_labels(df.columns)
```
which could potentially replace https://github.com/LBNL-ETA/Adapter/blob/95362e09d51a1a4d5dea768c842d6f49fd45cb73/adapter/i_o.py#L508

so that the Excel class is not needed https://github.com/LBNL-ETA/Adapter/blob/95362e09d51a1a4d5dea768c842d6f49fd45cb73/adapter/to_python.py#L21 

I haven't tried implementing the function to write named ranges, but reading named ranges and tables work just fine without opening Microsoft Excel program.

**Comment by milicag** [comment]
Did you run the unittests with your proposed solutions?

**Comment by lyralan** [comment]
@milicag I haven't done the unittests yet because I wasn't sure if this proposal would be adopted and I may need to consult with other developers since Adapter is being used across several models. If you think it's worthwhile, I'm happy to put efforts towards applying this solution to Adapter.

**Comment by milicag** [comment]
The tests I am referring to can be called as instructed in the `[Testing](https://github.com/LBNL-ETA/Adapter#testing)` section of the readme. This will ensure that all our common functionality is covered. I will not claim that the test coverage is 100%, but it is pretty safe to assume that every other user will not have issues with a feature that passes unittests - that is what those are constructed for! Please give them a try when you get a chance. This is what I would do to figure out if a feature is a good idea.

**Comment by lyralan** [comment]
> The tests I am referring to can be called as instructed in the [Testing](https://github.com/LBNL-ETA/Adapter#testing) section of the readme. This will ensure that all our common functionality is covered. I will not claim that the test coverage is 100%, but it is pretty safe to assume that every other user will not have issues with a feature that passes unittests - that is what those are constructed for! Please give them a try when you get a chance. This is what I would do to figure out if a feature is a good idea.

Sure! Would be happy to do so. I'll probably start on this tomorrow afternoon and will let you know when I'm done with the tests. Thanks!

**Comment by milicag** [comment]
I set up all unittests following that rule, mostly for simplicity of remembering how to run them for any of our packages.

**Comment by milicag** [comment]
@lyralan once you get to confirm that the unittests run fine, let @zhe1129 know so he can perform functional testing with inhouse packages.

**Comment by lyralan** [comment]
> @lyralan once you get to confirm that the unittests run fine, let @0xd5dc (Zheng) know so he can perform functional testing with inhouse packages.

@milicag The unittest for ```test_i_o.py``` ran successfully with my demo code showed above. The test was also ~15x faster.  ```test_to_python.py``` passed but is irrelevant because it tests the Excel class (which would be replaced by my proposal). 

@0xd5dc Hey Zheng - would you please perform other tests for my proposal for getting tables without opening excel files? Just FYI, https://github.com/LBNL-ETA/Adapter/issues/10#issuecomment-998356859 could be a potential substitute for Adapter.to_python.Excel. Please feel free to shoot me a message if you have any questions.

**Comment by milicag** [comment]
Thanks Lyra! Please the unittests pass, and you can test base lcc, shipper, nia, and LIDT with the new feature, it should be fine. I like the speed improvement, it will be useful. Also, please make sure that the functionality from to_python is covered with the change, unless deprecated by more optimized implementation.

@0xd5dc I can show you how to deploy once we demonstrate the readiness. You could deploy once we merge your new feature and this one.

**Comment by lyralan** [comment]
> 

@milicag @0xd5dc Sure. I'll let both of you know once I'm done with other models' unittests.

**Comment by 0xd5dc** [comment]
I studied this topic yesterday. So Pandas can load xlsx with openpyxl engine. Maybe we can use openpyxl divide a large dataframe into dict of dataframes.
```
 with pd.ExcelFile(file_path, engine="openpyxl") as xlfile:
        # Read a DataFrame
        df = pd.read_excel(xlfile, sheet_name="test")
```
Additionally, there is a parallel_pandas library, which can load large xlsx in parallel.

**Comment by lyralan** [comment]
> I studied this topic yesterday. So Pandas can load xlsx with openpyxl engine. Maybe we can use openpyxl divide a large dataframe into dict of dataframes.
> 
> ```
>  with pd.ExcelFile(file_path, engine="openpyxl") as xlfile:
>         # Read a DataFrame
>         df = pd.read_excel(xlfile, sheet_name="test")
> ```
> 
> Additionally, there is a parallel_pandas library, which can load large xlsx in parallel.

```openpyxl``` is what I'm using (please see the first line of my code). Since one excel sheet may have multiple named tables and named ranges, the original ```Adapter.to_python.Excel``` class was developed to read those from the workbook, https://github.com/LBNL-ETA/Adapter/blob/95362e09d51a1a4d5dea768c842d6f49fd45cb73/adapter/to_python.py#L91 not just reading sheets into DataFrames. As far as I know, Pandas would automatically use  ```openpyxl``` for excel files if you've installed it, but it doesn't handle  named tables and named ranges.

**Comment by milicag** [comment]
Right, the philosophy is to only look for tables and named ranges, while the sheets are for display purposes and organization mainly. Remember how in excel one can see a list of all named tables and ranges, or that "name manager" - that is what we fetch to read in. As if it was a database with those tables. We like to have the ability to only fetch some tables as well.

**Comment by 0xd5dc** [comment]
When pandas loads a xslx, the dataframe looks like regions of data surrounded by NaNs. I was able to extract all tables/ranges within a xslx using a bonding box algorithm. So the only problem became naming convention. I think we can get rid off xlwings completely.
```
    Unnamed: 0   Unnamed: 1  ...   Unnamed: 10  Unnamed: 11
0          NaN  Output Path  ...         col_2        col_3
1          NaN       output  ...             a           12
2          NaN          NaN  ...             b           13
3          NaN          NaN  ...             c           45
4          NaN          NaN  ...           NaN          NaN
5          NaN          NaN  ...           NaN          NaN
6          NaN          NaN  ...           NaN          NaN
7          NaN          NaN  ...        col_22       col_33
8          NaN          NaN  ...            aa          112
9          NaN          NaN  ...            bb          113
10         NaN          NaN  ...            cc          145
11         NaN          NaN  ...           NaN          NaN
12         NaN          NaN  ...           NaN          NaN
13         NaN          NaN  ...           NaN          NaN
14         NaN          NaN  ...  nam_ran_col2          NaN
15         NaN          NaN  ...          val3          NaN
16         NaN          NaN  ...          val4          NaN
17         NaN          NaN  ...           NaN          NaN
18         NaN          NaN  ...           NaN          NaN
19         NaN          NaN  ...           NaN         colA
20         NaN          NaN  ...           NaN            a
21         NaN          NaN  ...           NaN            b
22         NaN          NaN  ...           NaN            c
23         NaN          NaN  ...           NaN            d
24         NaN          NaN  ...           NaN          NaN
25         NaN          NaN  ...           NaN          NaN
26         NaN          NaN  ...           NaN          NaN
27         NaN          NaN  ...           NaN          NaN
```

**Comment by milicag** [comment]
@0xd5dc can you please explain the benefits of replacing xlwings? For instance, would your suggested approach be faster for our applications?

**Comment by 0xd5dc** [comment]
One of immediate benefits will avoiding the permission issue and minimizing user interaction on Mac. And, there wont be any excel to open while running the adapter. It probably will speed up our applications. Additionally, xlwings doesn't support Linux officially; our applications may have issues if we start using jupyterhub, which is designated for Linux deployment.

**Comment by milicag** [comment]
Thank you John, those are significant benefits.

**Comment by lyralan** [comment]
@0xd5dc @milicag This is what I'm doing in my code - reading a data frame and getting 'named' tables and ranges. Just FYI, this is only for reading inputs. I don't see any tests for writing, so I'm not sure if there's need to write named ranges. If so, we might need to implement the writing part without xlwings as well.

As @0xd5dc mentioned, it unifies Mac, Linux and Windows operation. Besides, the original Excel class using xlwings has hundreds of lines, whereas the new code provided above has only 50 lines, which makes it easier to maintain. I'd expect significant speed improvement especially in applications where many input files are read in, such as the pipeline.

**Comment by milicag** [comment]
Thanks @lyralan. These are good improvements.

Both, as regular practice, please test improved features as early on in the development as possible. It will save you time to assure minimum viability before adding perks.

**Comment by lyralan** [comment]
> Thanks Lyra! Once the unittests pass, and you can test base lcc, shipper, nia, and LIDT with the new feature, it should be fine. Zheng should be able to test the base code.

@milicag I've run all the tests for base lcc, shipper, nia and adapter, as well as those for wicf and cre shippers. Even using the current adapter code (with xlwings), there are three **unrelated** issues with lcc (not sure if this is because I'm using a Mac?). Using the proposed `openpyxl`-based code in this thread does not introduce any additional issues.

i) [`test_lcc_analysis.py`](https://bitbucket.org/eetd-ees/lcc/src/master/gen_lcc/tests/test_lcc_analysis.py) does not pass because one test file `/Volumes/ees/Cross-cutting APS/Programming/Test Files/Tester/ref_results/lcc/gen/382_main_2022_01_11-15h_38m.db` might have been corrupted and never finishes loading, thus [`test_perform_analysis()`](https://bitbucket.org/eetd-ees/lcc/src/fc5b66f6bcae293ac11d9b8f55ef9abd1be6ebd4/gen_lcc/tests/test_lcc_analysis.py#lines-149) fails. 

You can reproduce this issue by running
```
from adapter.i_o import IO
file = "/Volumes/ees/Cross-cutting APS/Programming/Test Files/Tester/ref_results/lcc/gen/382_main_2022_01_11-15h_38m.db"
IO(file).load(create_db=False, save_input=False, quick_db_out_filename="")
```
which is used in the test above.

ii) [`test_sample_assembler.py`](https://bitbucket.org/eetd-ees/lcc/src/master/gen_lcc/tests/test_sample_assembler.py) does not pass because of line [361](https://bitbucket.org/eetd-ees/lcc/src/fc5b66f6bcae293ac11d9b8f55ef9abd1be6ebd4/gen_lcc/tests/test_sample_assembler.py#lines-361), which triggers an error `float object does not have attribute 'round'`. This is an issue even if I'm using the original adapter code.

iii) [`test_label_map.py`](https://bitbucket.org/eetd-ees/lcc/src/master/gen_lcc/tests/test_label_map.py) does not pass because [`test_set_conf_labels()`](https://bitbucket.org/eetd-ees/lcc/src/fc5b66f6bcae293ac11d9b8f55ef9abd1be6ebd4/gen_lcc/tests/test_label_map.py#lines-428) fails. This is an issue with the original adapter code as well, and is totally unrelated to IO (it's just comparing two dictionaries). Regardless of the issue, it's not clear to me why there's a need to compare dictionaries in most of the tests in [`test_label_map.py`](https://bitbucket.org/eetd-ees/lcc/src/master/gen_lcc/tests/test_label_map.py).

Other than that, all other tests pass, with at least 2x speed improvement.

Also, I couldn't find a repo for LIDT on Bitbucket or Github, what is LIDT?

**Comment by milicag** [comment]
@lyralan I moved your latest comment to email. Thanks! Milica
