### ISSUE TITLE
Logger and note

### ISSUE THREAD

**Issue by milicag** [LBNL-ETA/Adapter#15]
Please address comments I provided here:

https://github.com/LBNL-ETA/Adapter/pull/11#pullrequestreview-838004710

**Comment by 0xd5dc** [comment]
Here is my example of logging when an error encountered. The caller will handle the exception and log the error, so there's no need to have logging.error() at the callee level.

```
def raise_error(name):
    # check if a file exists
    raise IOError("File not exists")

def handler():
    try:
        raise_error('where is the file')
    except Exception as err:
        logging.error(f" {err=}, {type(err)=}")

if __name__ == '__main__':
    logging.basicConfig(filename='run.log', level=logging.DEBUG)
    handler()
```

and the log file looks like this
`ERROR:root: err=OSError('File not exists'), type(err)=<class 'OSError'>`

**Comment by milicag** [comment]
Why is this better than just having the adapter package report the error?

**Comment by milicag** [comment]
We pass the logger between Python packages and rely on this in the log files.

**Comment by 0xd5dc** [comment]
> We pass the logger between Python packages and rely on this in the log files.
It will act the same because the way adapter's log configured here--using `__name__` variable will hold the name of the module (python file) that called the code.

**Comment by 0xd5dc** [comment]
> Why is this better than just having the adapter package report the error?

this approach captures error type and message, avoids redundant message passing(increases performance), and ensure the caller method handle the exception/error caused by the caller.
