### ISSUE TITLE
All keys are being checked for in the pre-existing keys, instead of just the table names that need to be read

### ISSUE THREAD

**Issue by a-sharma06** [LBNL-ETA/Adapter#17]
In the `load` function of class `Db`, duplicates of `keys` are being checked for. 
https://github.com/LBNL-ETA/Adapter/blob/master/adapter/to_python.py#L283

However, the docstring indicates that only `table_names` will be read from the database. Therefore, only duplicates of `table_names` should be checked for.

For reference, this issue didn't exist in v1.2.1.

**Comment by a-sharma06** [comment]
@lyralan @milicag @0xd5dc

**Comment by milicag** [comment]
@a-sharma06 Thanks for identifying and reporting the issue. @lyralan Is this something you can tackle? It looks like it could be a simple fix.

**Comment by lyralan** [comment]
@milicag It should be an easy fix, and I can make edits accordingly.

BTW, the [PR](https://github.com/LBNL-ETA/Adapter/pull/11/files#diff-2691406d9fa1eda73532b9e85df86dbc4f0f0fdf8724bad567bc39c1638ddf96L346) that @a-sharma06 found for `to_python.Db` has a version number v1.2.2. However, I didn't see a tag for v.1.2.2 when I made commits for `to_python.Excel` afterwards.

**Comment by lyralan** [comment]
I'm going to add a test for this case as well.

**Comment by lyralan** [comment]
This issue is addressed in [PR18](https://github.com/LBNL-ETA/Adapter/pull/18)
