### ISSUE TITLE
Update user_select_file to remove unnecessary dependencies

### ISSUE THREAD

**Issue by evaneill** [LBNL-ETA/Adapter#23]
The `user_select_file` will try to import either `win32ui, win32con`, or `tkinter` depending on `sys.platform`. But the win32ui and win32con seem to induce a dependency on `pywin32==225` that I see included in the `setup.py` of other tools that use this, which is undesirable. It appears that using later versions of pywin32 can result in an error on windows.

I imagine it is possible nowadays to find a single package (native or otherwise) that supports file prompt dialogs across OSX, windows, and linux. 

Low priority because it works as-is, but if managing dependencies for these imports can be a touch cumbersome now, it can only get worse in the future

**Comment by lyralan** [comment]
Closing this issue as it has been resolved
