### ISSUE TITLE
reformat folder name with timestamp

### ISSUE THREAD

**Issue by 0xd5dc** [LBNL-ETA/Adapter#28]
utilize the adapter to generate folder names with a timestamp in two formats, short format(default), and long format.
For example
|            long format            |      short format      |
|:---------------------------------:|:----------------------:|
|     prefix_2022_07_25-13h_50m     | abbr.ver._220725_1350 |
| product_version_branch_2022_08_02_14h_01m |    p100_220802_1401    |

**Comment by milicag** [comment]
The run parameters table, Version field value, provides the string that goes before the date and time, in your example `_220802_1401`. Let us, for start, try to keep the approach to the version string that comes from the run_parameters table the same between the long and the short, just to make it a bit easier. It might be useful to look at optionally pulling the code version from the code itself. For example, add a kwarg to optionally pass the LCC version in.
