### ISSUE TITLE
29_openpyxl_keep_vba

### ISSUE THREAD

**Issue by lyralan** [LBNL-ETA/Adapter#30]
`keep_vba` is set to True in Adapter's Excel class ([line](https://github.com/LBNL-ETA/Adapter/blob/b9ccaa0f4e215c11d50d2157f398e45220078efc/adapter/to_python.py#L39)), which revokes some zipfile methods and raise value error in a new connector PR ([link](https://bitbucket.org/eetd-ees/connector/pull-requests/23)). 

To solve this issue, just change `keep_vba` to `False`, as with `openpyxl`'s default. As far as I know, we only read non-visual data in Excel when running python tools (we don't normally have images in input files), setting `keep_vba` to `True` doesn't have an advantage over `False`. I'm wondering if @0xd5dc could just set this in the current open [PR](https://github.com/LBNL-ETA/Adapter/pull/29), as it's just a one line change? I can also make another PR if we treat it as a separate problem.

ps: `keep_vba` controls whether any Visual Basic elements (images and charts) are preserved or not (default). If preserved, they are not editable ([source](https://openpyxl.readthedocs.io/en/latest/usage.html?highlight=keep_vba#write-a-workbook-from-xltm-as-xlsm)).

**Comment by 0xd5dc** [comment]
sure, I'll change keep_vba's default value to false

**Comment by lyralan** [comment]
Thanks Zheng!

**Comment by milicag** [comment]
One comment, just to put it on our radar - we should think about ways to verify tables that get read into our DB. For example,  table names that are duplicates, apart from having one integer value added at the end, might indicate that someone randomly copied the table and forgot to edit the name, or it could be some old table that is not used any more. I'm not sure what is the best approach and whether it can be generalized in some way, without mandating a list of table names.
