### ISSUE TITLE
Simplify `comm.tools.user_select_file()` method

### ISSUE THREAD

**Issue by rhosbach** [LBNL-ETA/Adapter#42]
The `comm.tools.user_select_file()` is unnecessarily complex, and it relies on pywin32 for WIndows OS.  Ultimately, the functionality of this method can be achieved with the `tkinter` library (as is already implemented for OSX platform).

Using `tkinter` should make this method more robust and maintainable in the future.

**Comment by lyralan** [comment]
Closing this issue as it has been resolved.
