### ISSUE TITLE
Db always downloads all tables

### ISSUE THREAD

**Issue by evaneill** [LBNL-ETA/Adapter#9]
https://github.com/LBNL-ETA/Adapter/blob/95362e09d51a1a4d5dea768c842d6f49fd45cb73/adapter/to_python.py#L254

the `tables2dict` method doesn't take table_names, and will request all tables get loaded from the database no matter how much `load` is asked for.

Could super speed up asking for individual (or small subset of) tables in most cases by updating this.

The error for a requested table not existing could be moved down into tables2dict as well

**Comment by 0xd5dc** [comment]
tables2dict() in sql.py uses sqlite3 instead of sqlalchemy, executes SQL query to fetch table names. 
I know sqlalchemy has a function [MetaData.reflect()](https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.MetaData.reflect) may solve this issue

**Comment by milicag** [comment]
Sounds good to me, just make sure to quickly double-check we don't have this functionality hidden somewhere.

**Comment by milicag** [comment]
Is this addressed? If so, please close the issue. I'm not sure if you were aware of the practical Github perk: if you say, in the PR text, `Closes #x`, the issue is closed automatically.

**Comment by evaneill** [comment]
I didn't know about that feature, will use in the future
